fix: bug bash 20210802
blocklet/create-blocklet pull request #18
Opened 2021-08-05 23:26 UTC by LancelotLewis

2021-08-05 23:37 UTC, wangshijun requested changes

2021-08-05 23:37 UTC, wangshijun commented on .makefiles/bump_version.sh
> +#!/bin/bash
这里不能假设 bash 命令的位置，更稳妥的写法参照这里 https://stackoverflow.com/questions/21612980/why-is-usr-bin-env-bash-superior-to-bin-bash

2021-08-05 23:37 UTC, wangshijun commented on .makefiles/release.mk
> +#!/bin/bash
同上 https://stackoverflow.com/questions/21612980/why-is-usr-bin-env-bash-superior-to-bin-bash

2021-08-05 23:37 UTC, wangshijun commented on index.js
> +      // TODO: 如何获取未启动的 abtnode 实例目录？
这个是没办法获取到的，因为 abtnode 可以启动在任何有效的目录下面

2021-08-05 23:51 UTC, LancelotLewis commented on index.js
> +      // TODO: 如何获取未启动的 abtnode 实例目录？
我始终觉得有一个默认的运行目录会方便一些，这个可以等之后让一些开发者使用后再根据实际情况来决定怎么改进

2021-08-06 00:27 UTC, wangshijun approved these changes

2021-08-06 00:27 UTC, merged