feat: add support monorepo template
blocklet/create-blocklet pull request #185
Opened 2022-09-17 04:38 UTC by frmachao

### 关联 Issue

### 主要改动

1. 修复了 xxx
2. 改进了 xxx
3. 调整了 xxx

### 界面截图

### 检查清单

2022-09-17 07:56 UTC, wangshijun commented
> * 完善 create-blocklet 的文档站点，替换首页站点上的 录屏截图
>   - 这个要等到发布之后？

应该发布之前就更新

2022-09-17 07:57 UTC, wangshijun commented
另外， @frmachao 建议把每个 dapp 项目的名字写的更加具体，比如 dapp 是组合了哪些技术栈实现的，react + express.js

2022-09-17 08:02 UTC, mave99a commented
要思考一下这里的每一个template 是放在自己的repo里（然后比如submodule）好呢，还是放在一个里呢？

这个template 用户可以很容易贡献吗？  比如做一个ethereum的，或者一个solana的等

2022-09-19 04:05 UTC, frmachao commented
> 另外， @frmachao 建议把每个 dapp 项目的名字写的更加具体，比如 dapp 是组合了哪些技术栈实现的，react + express.js 等等

已处理

2022-09-19 07:34 UTC, LancelotLewis requested changes

2022-09-19 07:34 UTC, LancelotLewis commented on packages/create-app/templates/monorepo/.makefiles/release.mk
> +#!/usr/bin/env bash
我看有同时存在 bump-version.js 文件，应该只需要采用一种方式即可？

2022-09-19 07:34 UTC, LancelotLewis commented on packages/create-app/templates/monorepo/.npmrc
> +shamefully-hoist=true
将 `shamefully-hoist=true` 改为 `node-linker=hoisted`
https://pnpm.io/zh/npmrc#node-linker

仅使用 `shamefully-hoist=true` 的情况下，全栈项目 bundle 出来的结果貌似无法运行在 blocklet-server 中

或者现在已经测试过全栈项目 bundle 后是能够正常运行的？

2022-09-19 08:32 UTC, frmachao commented on packages/create-app/templates/monorepo/.makefiles/release.mk
> +#!/usr/bin/env bash
已处理，目前采用了  bump-version.js  的方案

2022-09-19 09:39 UTC, frmachao commented on packages/create-app/templates/monorepo/.npmrc
> +shamefully-hoist=true
目前在 monorepo 类型的模板中已经移除掉了 .npmrc  因为当前使用 yarn + lerna 来管理 monorepo 的；
但是现在  monorepo 类型项目 deploy 时存在问题，dapp 的项目 部署上去后页面后显示。404 nof found, 待处理

2022-09-20 03:14 UTC, frmachao commented on packages/create-app/lib/utils.js
> +export async function checkLearn() {
已处理

2022-09-20 03:26 UTC, LancelotLewis approved these changes

2022-09-20 04:08 UTC, merged