fix: bugbash-0921
blocklet/create-blocklet pull request #196
Opened 2022-09-21 16:17 UTC by frmachao

### 关联 Issue

fixes:
- https://github.com/blocklet/create-blocklet/issues/188
- https://github.com/blocklet/create-blocklet/issues/189
- https://github.com/blocklet/create-blocklet/issues/190
- https://github.com/blocklet/create-blocklet/issues/191
- https://github.com/blocklet/create-blocklet/issues/192
- https://github.com/blocklet/create-blocklet/issues/193
- https://github.com/ArcBlock/blocklet-server/issues/5552

### 主要改动

修复 bugbash 中发现的问题；
未处理： https://github.com/blocklet/create-blocklet/issues/194
 如果一个 dapp 作为子组件，在 dev 模式下，无法正确访问后 api 接口

### 界面截图

### 检查清单

2022-09-21 16:46 UTC, LancelotLewis requested changes

2022-09-21 16:46 UTC, LancelotLewis commented on packages/create-app/index.js
> +        if (mainBlocklet && !['screenshots', 'public', 'logo.png', '_prettierrc'].includes(file)) {
如果确定能溢出 renameFiles 逻辑，则 `_prettierrc` -> `.prettierrc`

2022-09-22 02:32 UTC, frmachao commented on packages/create-app/index.js
> +        if (mainBlocklet && !['screenshots', 'public', 'logo.png', '_prettierrc'].includes(file)) {
已处理

2022-09-22 02:32 UTC, frmachao commented on packages/create-app/index.js
> -
已恢复

2022-09-22 02:56 UTC, LancelotLewis approved these changes

2022-09-22 03:01 UTC, merged