feat: replace makefile and bash script with npm script and zx in react-dapp template
blocklet/create-blocklet pull request #229
Opened 2022-10-17 11:28 UTC by polunzh

### 关联 Issue

relates https://github.com/ArcBlock/blocklet-server/issues/3591

### 主要改动

1. 修复了 xxx
2. 改进了 xxx
3. 调整了 xxx

### 界面截图

### 检查清单

2022-10-17 12:13 UTC, LancelotLewis requested changes
bump-version 和 clean 对于所有的 template 应该都是适用的？

2022-10-17 12:13 UTC, LancelotLewis commented on packages/create-app/common/scripts/build-clean.mjs
> +await $`rm -rf .blocklet`;
删除文件夹使用这个包，可以直接跨平台 https://www.npmjs.com/package/rimraf

`rm` 本身应该是不支持 windows 下使用的

2022-10-17 12:36 UTC, skypesky commented on packages/create-app/common/scripts/build-clean.mjs
> +await $`rm -rf .blocklet`;
> 我测试过可以在 windows 下用。
用的是cmd吗？

2022-10-17 13:04 UTC, polunzh commented on packages/create-app/common/scripts/build-clean.mjs
> +await $`rm -rf .blocklet`;
> 我测试过可以在 windows 下用。
不应该使用 rm. 我的 windows 因为安装了 wsl, 导致有 bash, zx 会优先用 bash.

2022-10-17 13:38 UTC, polunzh commented on packages/create-app/common/scripts/build-clean.mjs
> +await $`rm -rf .blocklet`;
https://github.com/blocklet/create-blocklet/pull/229/commits/cbf251c7613a15c9b50ea58083b4ecf984155268

2022-10-19 03:27 UTC, wangshijun commented
> bump-version 和 clean 对于所有的 template 应该都是适用的？

@frmachao monorepo 情形请你在之后的 pr 里面处理

2022-10-19 03:29 UTC, polunzh commented
> > bump-version 和 clean 对于所有的 template 应该都是适用的？
> 
> @frmachao monorepo 情形请你在之后的 pr 里面处理

我现在判断这个脚本对非 monorepo 都是有效的。

2022-10-19 03:39 UTC, wangshijun approved these changes

2022-10-19 03:40 UTC, merged