Feature:nestjs template
blocklet/create-blocklet pull request #284
Opened 2023-05-22 18:05 UTC by vmcodes

This needs a code review and testing, but I was able to run the NestJS template Blocklet locally. It is very similar to the Express template Blocklet.

Please let me know of any next steps, or anything that I could have done myself. 

Thank you.

2023-05-22 21:57 UTC, wangshijun commented
@vmcodes Thanks for the contribution!

blocklet projects created from the new template should meet the following requirements

- [ ] can be bundled with `npm run bundle`
- [ ] can be deployed with `npm run deploy`
- [ ] bump patch version with `npm run bump-version`

Since blocklet server 1.16.0, the correct steps to deploy a blocklet should be:

1. create an app container from your server dashboard
![Screenshot 2023-05-23 at 05 52 47](https://github.com/blocklet/create-blocklet/assets/719985/1351225e-05b7-497a-a58a-f08e38babfa7)

2. get the appDid of the newly created app
![image](https://github.com/blocklet/create-blocklet/assets/719985/2e4d560d-226d-4f46-b5b7-cd6ca0f21965)

3. run `blocklet deploy .blocklet/bundle --app-did={your-app-did} --mount-point=/` and then try to start your app
4. ensure the running app works as expected
5. then we are ready to 

please help to ensure the above checklist before we can merge and release.

2023-05-23 22:38 UTC, vmcodes commented
@wangshijun Thank you, I updated some of the code and had no issues deploying the template. Please let me know if anything needs to be changed.

![nestjs-template-test](https://github.com/blocklet/create-blocklet/assets/30095385/30bce49f-9723-4004-a74f-6bf8bf3233d5)

2023-05-24 02:47 UTC, LancelotLewis requested changes
Please add this code in `/packages/create-app/index.js` L121
you can see `[API] nestjs` when use `blocklet create` command

``` js
{
  name: 'nestjs-api',
  display: '[api] nestjs',
  color: yellow,
},
```

2023-05-24 02:47 UTC, LancelotLewis commented on packages/create-app/templates/nestjs-api/.env
> +APP_TITLE=''
If you don't use this env, you can remove this file

2023-05-24 02:47 UTC, LancelotLewis commented on packages/create-app/templates/nestjs-api/README.md
> +  - index.js - Api side entry point
Please change this folder structure as this template is

2023-05-24 05:32 UTC, vmcodes commented
@LancelotLewis thanks for your patience. The new updates should be correct. Let me know.

2023-05-24 05:33 UTC, LancelotLewis approved these changes

2023-05-24 05:36 UTC, merged