feat(create-app): add vue3 typescript static template
blocklet/create-blocklet pull request #349
Opened 2024-08-06 06:23 UTC by keyding

### Relates Issue

#348 

### Main changes

Adding Vue3 TypeScript Static template project.

### Screenshots

Choose template:
![choose-template](https://github.com/user-attachments/assets/42e53e71-56cf-4310-88cb-01c48e9944c8)

Generate Project:
![generate-project](https://github.com/user-attachments/assets/00ec2195-bb5a-48bf-a805-b2a27e42e1b5)

### Check list

- [x] Project create by create-blocklet can work with `npm run dev`
- [x] Project create by create-blocklet can work with `npm run deploy`
- [x] Project create by create-blocklet can work with `npm run upload`
- [x] If a new version need to be publish, make sure you have run `npm run bump-version` command

2024-08-06 06:31 UTC, LancelotLewis requested changes

2024-08-06 06:31 UTC, LancelotLewis commented on packages/create-app/templates/vue-ts-static/blocklet.yml
> +did: z8iZh3SGuBsFsBW9TFk6paXCQUfDaapfJAYjN
did field in template should be empty

2024-08-06 06:41 UTC, keyding commented on packages/create-app/templates/vue-ts-static/blocklet.yml
> +did: z8iZh3SGuBsFsBW9TFk6paXCQUfDaapfJAYjN
OK. The did field has been cleared.

2024-08-06 08:49 UTC, LancelotLewis approved these changes
LGTM

2024-08-07 02:45 UTC, LancelotLewis commented
@keyding
you need to run `npm run bump-version` in this project folder

2024-08-07 14:09 UTC, keyding commented
> @keyding you need to run `npm run bump-version` in this project folder

Yes, I'm done.

2024-08-09 01:31 UTC, LancelotLewis commented
@keyding Please bump-version again 🤣

2024-08-09 06:50 UTC, keyding commented
> @keyding Please bump-version again 🤣

Done.

2024-08-09 09:54 UTC, merged