feat(template): add did wallet dapp template
blocklet/create-blocklet pull request #361
Opened 2024-09-25 08:04 UTC by xiaomoziyi

### Relates Issue

### Main changes

1. 新增 did wallet dapp 模板
2. 优化: 新增mergeReadme, 将重复性Readme 单独提取到公共部分，支持
  - 通过变量覆盖 base-readme 变量内容
  ```md
    ## PROJECT_DESCRIPTION
   项目描述
    ## FILE_STRUCTURE
   文件结构
  ``` 
  - 段落变量名一致覆盖 base-readme 原有段落内容
  ```md
  ## Development
  这里的内容将覆盖原有的 development 段落
  // 如果为空，表示去除原有的 development 段落
  ``` 
需注意，变量或者段落覆盖，都是 `## [name]` 二级标题来识别

### Screenshots
create:
<img width="1302" alt="image" src="https://github.com/user-attachments/assets/cbad428f-e8ab-4453-ae8c-8cf73bcf581d">

首页：
![image](https://github.com/user-attachments/assets/579aef35-3c0c-4f1d-9410-f21e4f3fa362)

个人信息：
<img width="2565" alt="image" src="https://github.com/user-attachments/assets/5d2dfb6c-ba69-4867-ba92-fa47dd87ac26">

未登录：
<img width="2571" alt="image" src="https://github.com/user-attachments/assets/23748991-23d3-483a-be08-d7e6aa63c9ed">

profile:
<img width="1687" alt="image" src="https://github.com/user-attachments/assets/b53985ac-66d6-4118-a5ed-7d4cd18eed2e">

### Check list

- [x] Project create by create-blocklet can work with `npm run dev`
- [x] Project create by create-blocklet can work with `npm run deploy`
- [x] Project create by create-blocklet can work with `npm run upload`
- [x] If a new version need to be publish, make sure you have run `npm run bump-version` command

2024-09-25 08:56 UTC, wangshijun requested changes

2024-09-25 08:56 UTC, wangshijun commented on packages/create-app/index.js
> +    display: '[dapp: did-wallet] react + express + DID Wallet',
react + express + DID Wallet --> Full stack app (react.js + express.js) with DID Wallet integration

2024-09-25 08:56 UTC, wangshijun commented on packages/create-app/templates/did-wallet-dapp/README.md
> +   See details in [https://www.arcblock.io/docs/blocklet-developer/getting-started](https://www.arcblock.io/docs/blocklet-developer/getting-started)
所有文档的 L51 的链接都不对，应该指向： https://www.arcblock.io/docs/blocklet-developer/install-blocklet-cli#start-blocklet-server

这个文档可以帮忙看下是否需要更新

2024-09-25 08:56 UTC, wangshijun commented on packages/create-app/templates/did-wallet-dapp/README.md
> +   `blocklet server init --mode=debug`
--mode=debug 可以去掉，全部替换吧

2024-09-25 08:56 UTC, wangshijun commented on packages/create-app/templates/did-wallet-dapp/README.md
> +   See details in [https://www.arcblock.io/docs/blocklet-developer/install-blocklet-cli](https://www.arcblock.io/docs/blocklet-developer/install-blocklet-cli)
这里指向的文档也需要更新下

2024-09-25 08:56 UTC, wangshijun commented on packages/create-app/templates/did-wallet-dapp/README.md
> +  1. [https://store.blocklet.dev/](https://store.blocklet.dev/)
这里优先 放 test store，因为其他两个 store 需要邀请

2024-09-25 08:56 UTC, wangshijun commented on packages/create-app/templates/did-wallet-dapp/README.md
> +  ```
这两部直接合成为 blocklet connect？

2024-09-25 08:56 UTC, wangshijun commented on packages/create-app/templates/did-wallet-dapp/README.md
> +   Replace `did` field in the `blocklet.yml`
这个应该去掉？ @LancelotLewis

2024-09-25 08:56 UTC, wangshijun commented on packages/create-app/templates/did-wallet-dapp/api/routes/user.js
> +    app.get('/api/did/user', middlewares.user(), async (req, res) => {
middlewares.user() --> middlewares.session()

2024-09-25 08:56 UTC, wangshijun commented on packages/create-app/templates/did-wallet-dapp/api/routes/user.js
> +    app.get('/api/did/user', middlewares.user(), async (req, res) => {
另外，这两个 api 保留1个即可？

2024-09-25 08:56 UTC, wangshijun commented on packages/create-app/templates/did-wallet-dapp/blocklet.md
> +# template-did-wallet-dapp
这里应该更新下

比如改成更加明显的： Please update this

2024-09-25 08:59 UTC, LancelotLewis commented on packages/create-app/templates/did-wallet-dapp/README.md
> +   Replace `did` field in the `blocklet.yml`
去掉，我准备移除模板的 name 字段，默认让它 fallback 到 did

2024-09-25 09:03 UTC, LancelotLewis commented on packages/create-app/templates/did-wallet-dapp/src/app.jsx
> +        <SessionProvider serviceHost={prefix}>
serviceHost 目前已经有默认值了，可以不传递它

2024-09-25 09:10 UTC, wangshijun commented
> blocklet 运行：

这里需要加1个正常的页面，目前这个页面是用了 profile layout？

模拟1个正常应用：

- 登陆前
- 登录后：功能区
- 登录后：个人中心

2024-09-25 15:11 UTC, xiaomoziyi commented on packages/create-app/templates/did-wallet-dapp/README.md
> +  1. [https://store.blocklet.dev/](https://store.blocklet.dev/)
改成test store示例了

2024-09-25 15:12 UTC, xiaomoziyi commented on packages/create-app/templates/did-wallet-dapp/api/routes/user.js
> +    app.get('/api/did/user', middlewares.user(), async (req, res) => {
等server发版再调整

2024-09-26 01:37 UTC, xiaomoziyi commented on packages/create-app/test2/README.md
> +# Getting Started with Create Blocklet
漏删了 = =

2024-09-26 01:45 UTC, xiaomoziyi commented on packages/create-app/templates/did-wallet-dapp/blocklet.yml
> +name: template-did-wallet-dapp
先不处理

2024-09-26 02:52 UTC, LancelotLewis approved these changes

2024-09-26 02:54 UTC, wangshijun approved these changes

2024-09-26 02:54 UTC, merged